#note, key create and encrypt notes can be found in here https://gist.github.com/jesgs/7815f791c98ea2f3e82c51f5c66b6ce1 but recall this set for goober is just copies of what was made for ReactResume
language: go
go:
- "1.12"
dist: xenial
# services:
#   - docker
sudo: false
addons:
  ssh_known_hosts:
  - chws.ca
before_install:
- openssl aes-256-cbc -K $encrypted_db28af1a7c5c_key -iv $encrypted_db28af1a7c5c_iv -in .travis/deploy_rsa.enc -out .travis/deploy_rsa -d
- openssl aes-256-cbc -K $encrypted_552af73186a2_key -iv $encrypted_552af73186a2_iv -in docker/config/invoice.macaroon.enc -out invoice.macaroon -d
- eval "$(ssh-agent -s)"
- cp .travis/deploy_rsa ~/.ssh/deploy_rsa
- chmod 600 ~/.ssh/deploy_rsa
- ssh-add ~/.ssh/deploy_rsa
- echo -e "Host chws.ca\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config

before_script:
  - printenv
  - ls -l $GOPATH/src/

script:
  # note, at the time of this writing i have no tests in this thing. all it does is integrate with stuff so not sure what kind of test i'd write.
  - git rev-parse HEAD
  - git reset --hard
  - git pull
  - git rev-parse HEAD
  - go test -v ./...
  - go build
  - sha1sum goober
  - touch restart

deploy:
- provider: script
  skip_cleanup: true
  script: ".travis/deploy.sh"
  on:
    branch: master

cache:
  directories:
    - $GOPATH/bin
    - $GOPATH/pkg
    - $GOPATH/src
    - $HOME/.cache/go-build
    # - $HOME/gopath/pkg/mod    